---

- name: Install Apache2 + deploy custom site
  hosts: staging_servers
  become: yes

  vars:
    sourse_site: ./site/index.html
    dest_site: /var/www/html/index.html

  tasks:
   - name: Install apache2
     apt: name=apache2  state=latest

   - name: copy site to clients
     copy: src={{sourse_site}} dest={{dest_site}}
     notify: restart_apache # выполнится только если не пропущен таск

   - name: start apache server
     service: name=apache2 state=started enabled=yes

   - name: Debug Finish Message
     debug:
      msg: "Deploy from user {{ owner }}"

# handlers - описание доп. команды
  handlers:
    - name: restart_apache
      service: name=apache2 state=restarted
