
---

- name: Ansible Vault
  hosts: ubuntu_server2, centos_server2
  become: yes

  vars:
    - password: qwe123

  tasks:
    - name: Create config
      ansible.builtin.copy:
        dest: /home/config.cfg
        content: |
          hostname: {{inventory_hostname}}
          data: data_data
          pass: {{password}}